# Generated by Django 2.2.6 on 2019-12-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_authorpost_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorpost',
            old_name='user_type',
            new_name='user_typ',
        ),
    ]
