# Generated by Django 2.2.6 on 2019-12-15 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20191215_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorpost',
            name='user_typ',
        ),
        migrations.AddField(
            model_name='authorpost',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
