# Generated by Django 2.2.6 on 2019-12-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191215_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorpost',
            name='user_type',
        ),
    ]
