# Generated by Django 2.2.6 on 2019-12-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_authorpost_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorpost',
            name='uid',
        ),
    ]
