# Generated by Django 2.2.6 on 2019-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_authorpost_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpost',
            name='user_profile_link',
            field=models.URLField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
